name: unit-tests
on: [push, pull_request]
jobs:
  es5-initial:
    name: 00-es5-initial
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: yarn
      - run: cd 00-es5-initial; yarn install
      - run: cd 00-es5-initial; yarn test

  es5-added-lint:
    name: 01-es5-added-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: yarn
      - run: cd 01-es5-added-lint; yarn install
      - run: cd 01-es5-added-lint; yarn test

  es6-initial:
    name: 10-es6-initial
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: yarn
      - run: cd 10-es6-initial; yarn install
      - run: cd 10-es6-initial; yarn test

  es6-added-lint:
    name: 11-es6-added-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: yarn
      - run: cd 11-es6-added-lint; yarn install
      - run: cd 11-es6-added-lint; yarn test

  ts-initial:
    name: 20-ts-initial
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: yarn
      - run: cd 20-ts-initial; yarn install
      - run: cd 20-ts-initial; yarn test

  ts-added-lint:
    name: 21-ts-added-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: yarn
      - run: cd 21-ts-added-lint; yarn install
      - run: cd 21-ts-added-lint; yarn test

  ts-usecase-common:
    name: 22-ts-usecase-common
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: yarn
      - run: cd 22-ts-usecase-common; yarn install
      - run: cd 22-ts-usecase-common; yarn test
